vim.keymap.set("n", "<leader>pv", vim.cmd.Ex)
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "<leader>dp", function() require('dap').toggle_breakpoint() end)
vim.keymap.set("n", "<leader>dr", function() require('dap').continue() end)
vim.keymap.set("n", "<leader>dt", function() require('dapui').toggle() end)
vim.keymap.set("n", "<leader>pt", ":split term://zsh<CR>")
